
export const headerNav = [
    {
        title: "투데이",
        url: "/",
        class:"link_today b4icons",
    },
    {
        title: "차트",
        url: "/chart",
        class:"link_chart b4icons",
    },
    {
        title: "최신앨범",
        url: "#none",
        class:"link_newalbum b4icons",
    },
    {
        title: "DJ 스테이션",
        url: "#none",
        class:"link_dj b4icons",
    },
    {
        title: "VIBE MAG",
        url: "#none",
        class:"link_mag b4icons",
    },
    {
        title: "이달의 노래",
        url: "#none",
        class:"link_monthly b4icons",
    },
    /* {
        title: "보관함",
        url: "#none",
        class:"",
    }, */
    {
        title: "서비스 소개",
        url: "#none",
        class:"link_about b4icons",
    },
    {
        title: "내돈내듣",
        url: "#none",
        class:"link_wheresmymoney b4icons",
    },
    {
        title: "VIBE 오디오",
        url: "#none",
        class:"link_audio b4icons",
    },
    
];
// TodaySection
export const magazine = [
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #175",
        mgzTit2:"빌리조엘",
        mgzitem:"2024.01.23",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
    {
        mgzImg: require("../assets/images/andro1.jpg"),
        mgzTit1:"이주의 디깅 #176",
        mgzTit2:"더 키드 라로이",
        mgzitem:"2024.02.05",
        url: "#none",
    },
];
export const newSection = [
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg1.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다1",
        url: "#none",
    },
    {
        newsImg: require("../assets/images/newsImg.png"),
        newsTit1:"르세라핌의 신곡 ‘EASY’가 23일 영어 음원으로 발매됩니다",
        url: "#none",
    },
];
export const playList = [
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘이곡",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘아이돌",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘이곡",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘아이돌",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘이곡",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘아이돌",
        sub:"VIBE",
        url: "#none",
    },{
        Img: require("../assets/images/TREND_VIBE_Pick_1214.jpg"),
        Tit1:"요즘이곡",
        sub:"VIBE",
        url: "#none",
    },
    {
        Img: require("../assets/images/1703838920611.jpg"),
        Tit1:"이달의 발라드(2023/12)",
        sub:"VIBE 트렌드",
        url: "#none",
    },

];

// 차트 - 오늘 Top 100
// rank 1 - 15
export const chartTop15 = [
    {
        rankNum : "1",
        title: "밤양갱",
        artist: "비비(BIBI)",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"밤양갱 앨범 커버",
    },
    {
        rankNum : "2",
        title: "Love wins all",
        artist: "아이유(IU)",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"The Winning 앨범 커버",
    },
    {
        rankNum : "3",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "4",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "5",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "6",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "7",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "8",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "9",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "10",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "11",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },
    {
        rankNum : "12",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "13",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "14",
        title: "No One No One No OneNo OneNo One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "15",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },
]
export const chartTop30 = [
    {
        rankNum : "16",
        title: "밤양갱",
        artist: "비비(BIBI)",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"밤양갱 앨범 커버",
    },
    {
        rankNum : "17",
        title: "Love wins all",
        artist: "아이유(IU)",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"The Winning 앨범 커버",
    },
    {
        rankNum : "18",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "19",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "20",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "21",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "22",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "23",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "24",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "25",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/796/30796788.jpg?type=r100Fll&v=20240223101020",
        alt:"No One",
    },
    {
        rankNum : "26",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },
    {
        rankNum : "27",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "28",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "29",
        title: "No One No One No OneNo OneNo One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },{
        rankNum : "30",
        title: "No One",
        artist: "No One",
        url:"#none",
        src:"https://musicmeta-phinf.pstatic.net/album/030/864/30864083.jpg?type=r100Fll&amp;v=20240222100046",
        alt:"No One",
    },
]